name: App_Ventas_Hob
description: "Aplicación de ventas con sincronización, base de datos local y exportación a PDF."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter: 
    sdk: flutter
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  http: ^1.1.0
  intl: ^0.18.1
  url_launcher: ^6.1.14
  shared_preferences: ^2.2.2
  pdf: ^3.10.4          # <-- NUEVO: Para crear el diseño del PDF
  printing: ^5.11.0      # <-- NUEVO: Para previsualizar, compartir e imprimir el PDF

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
